"""revised table update

Revision ID: 03239deb01fb
Revises: 69773060f0f9
Create Date: 2024-07-04 14:58:21.797547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03239deb01fb'
down_revision: Union[str, None] = '69773060f0f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('occupation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'occupation')
    # ### end Alembic commands ###
